# Generated by Django 4.2.5 on 2023-12-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_headline_alter_kategori_id_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iklan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='iklan_pics')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_deskripsi',
            field=models.TextField(null=True, verbose_name='Caption'),
        ),
    ]
