# Generated by Django 4.2.5 on 2023-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_iklan_alter_post_meta_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='iklan',
            name='nomor_iklan',
            field=models.IntegerField(default=1),
        ),
    ]
