# Generated by Django 4.2.5 on 2023-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_dokumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='program_pendidikan',
            field=models.CharField(choices=[('SMP', 'SMP'), ('SMA', 'SMA')], default='SMP', max_length=3),
        ),
    ]
