# Generated by Django 4.2.5 on 2023-12-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_dokumen_program_pendidikan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iklan',
        ),
    ]
