# Generated by Django 4.2.5 on 2023-12-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_iklan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Terverifikasi'), ('terverifikasi', 'Terverifikasi')], default='belum', max_length=20),
        ),
    ]
